version: "3.7"

services:
  birthday-greeter-solid-kata-php:
    container_name: birthday-greeter-solid-kata-fpm
    image: birthday-greeter-solid-kata-php
    env_file:
      - .env
    build:
      dockerfile: ./docker/php/Dockerfile
      context: .
    volumes:
      - .:/var/www/birthday-greeter-solid-kata
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini